# Generated by Django 4.2.7 on 2023-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmluserinfo",
            name="birthday",
        ),
        migrations.AlterField(
            model_name="mmluserinfo",
            name="age_range",
            field=models.CharField(max_length=10),
        ),
    ]
