# Generated by Django 4.2.7 on 2023-11-17 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_mmlusergen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mmlusergen",
            old_name="username",
            new_name="user_info",
        ),
    ]
