# Generated by Django 4.2.7 on 2023-11-17 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_username_mmlusergen_user_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mmlusergen",
            name="user_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
