# Generated by Django 4.2.7 on 2023-11-17 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_mmlusergen_user_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmlusergen",
            name="user_info",
        ),
        migrations.AddField(
            model_name="mmlusergen",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
