# Generated by Django 4.2.7 on 2023-11-17 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_mmlusergen_user_info_mmlusergen_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMLUserLikeArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gen", models.CharField(max_length=10)),
                ("age_group", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "mml_user_like_artist",
            },
        ),
    ]
