# Generated by Django 4.2.7 on 2023-11-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_mmluserlikeartist"),
    ]

    operations = [
        migrations.CreateModel(
            name="MMLArtistGen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("artist", models.CharField(max_length=100)),
                ("priority", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("artist_processed", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "mml_artist_gen",
            },
        ),
        migrations.AlterField(
            model_name="mmluserlikeartist",
            name="artist",
            field=models.ForeignKey(
                db_column="artist_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.mmlartistgen",
            ),
        ),
    ]
